SET DB_CLOSE_DELAY -1;
CREATE USER IF NOT EXISTS SA SALT 'ab0ed27f996508d0' HASH 'af887f21de32f26348737985813cb0ca11c2c3e766a001a347de743ca97ae7d3' ADMIN;
CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 33;
CREATE CACHED TABLE PUBLIC.CMR(
    ID BIGINT NOT NULL,
    ABFERTIGUNGSDATUM VARCHAR(255),
    ABFERTIGUNGSORT VARCHAR(255),
    AKTIV BOOLEAN NOT NULL,
    BELADUNGSDATUM VARCHAR(255),
    BELADUNGSORTLAND VARCHAR(255),
    BELADUNGSORTPLZ VARCHAR(255),
    CREATIONTIME TIMESTAMP,
    ENTLADUNGSORTLAND VARCHAR(255),
    ENTLADUNGSORTPLZ VARCHAR(255),
    KFZANHAENGER VARCHAR(255),
    KFZLKW VARCHAR(255),
    LADUNGEINHEIT VARCHAR(255),
    LADUNGGEWICHT VARCHAR(255),
    LADUNGTEXT VARCHAR(255),
    PRINTABSENDERFORUNTERSCHRIFT BOOLEAN NOT NULL,
    ABSENDER_ID BIGINT,
    EMPFAENGER_ID BIGINT
);
ALTER TABLE PUBLIC.CMR ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.CMR;
INSERT INTO PUBLIC.CMR(ID, ABFERTIGUNGSDATUM, ABFERTIGUNGSORT, AKTIV, BELADUNGSDATUM, BELADUNGSORTLAND, BELADUNGSORTPLZ, CREATIONTIME, ENTLADUNGSORTLAND, ENTLADUNGSORTPLZ, KFZANHAENGER, KFZLKW, LADUNGEINHEIT, LADUNGGEWICHT, LADUNGTEXT, PRINTABSENDERFORUNTERSCHRIFT, ABSENDER_ID, EMPFAENGER_ID) VALUES
(2, '15.01.2017', '', TRUE, '15.01.2017', 'AUT', '1', NULL, 'AUT', '1', 'KR 819 CL', 'KR 747 AJ', '', '', 'Tpa 1561465, Taubitz Bio Mais sdsdfsdf', FALSE, 1, 1);
CREATE CACHED TABLE PUBLIC.CMRANSCHRIFT(
    ID BIGINT NOT NULL,
    AKTIV BOOLEAN NOT NULL,
    LINE1 VARCHAR(255),
    LINE2 VARCHAR(255),
    LINE3 VARCHAR(255),
    LINE4 VARCHAR(255)
);
ALTER TABLE PUBLIC.CMRANSCHRIFT ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.CMRANSCHRIFT;
INSERT INTO PUBLIC.CMRANSCHRIFT(ID, AKTIV, LINE1, LINE2, LINE3, LINE4) VALUES
(1, TRUE, '1', '1', '1', '1');
CREATE CACHED TABLE PUBLIC.RECHNUNG(
    ID BIGINT NOT NULL,
    FAELLIGAM DATE,
    RECHNUNGSDATUM DATE,
    ANSCHRIFT_ID BIGINT
);
ALTER TABLE PUBLIC.RECHNUNG ADD CONSTRAINT PUBLIC.CONSTRAINT_FE PRIMARY KEY(ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.RECHNUNG;
INSERT INTO PUBLIC.RECHNUNG(ID, FAELLIGAM, RECHNUNGSDATUM, ANSCHRIFT_ID) VALUES
(5, DATE '2017-02-15', DATE '2017-01-15', 3);
CREATE CACHED TABLE PUBLIC.RECHNUNG_ZEILE(
    RECHNUNG_ID BIGINT NOT NULL,
    ZEILE_ID BIGINT NOT NULL
);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.RECHNUNG_ZEILE;
INSERT INTO PUBLIC.RECHNUNG_ZEILE(RECHNUNG_ID, ZEILE_ID) VALUES
(5, 4);
CREATE CACHED TABLE PUBLIC.RECHNUNGSANSCHRIFT(
    ID BIGINT NOT NULL,
    AKTIV BOOLEAN NOT NULL,
    LINE1 VARCHAR(255),
    LINE2 VARCHAR(255),
    LINE3 VARCHAR(255),
    LINE4 VARCHAR(255)
);
ALTER TABLE PUBLIC.RECHNUNGSANSCHRIFT ADD CONSTRAINT PUBLIC.CONSTRAINT_C PRIMARY KEY(ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.RECHNUNGSANSCHRIFT;
INSERT INTO PUBLIC.RECHNUNGSANSCHRIFT(ID, AKTIV, LINE1, LINE2, LINE3, LINE4) VALUES
(3, TRUE, 'Daniela Teuschl', 'Habruck 31', '3611 Habruck', '');
CREATE CACHED TABLE PUBLIC.RECHNUNGSZEILE(
    ID BIGINT NOT NULL,
    BESCHREIBUNG VARCHAR(255),
    MENGE DOUBLE,
    SATZ DOUBLE
);
ALTER TABLE PUBLIC.RECHNUNGSZEILE ADD CONSTRAINT PUBLIC.CONSTRAINT_14 PRIMARY KEY(ID);
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.RECHNUNGSZEILE;
INSERT INTO PUBLIC.RECHNUNGSZEILE(ID, BESCHREIBUNG, MENGE, SATZ) VALUES
(4, 'Tpa 1561465, Taubitz Bio Mais sdsdfsdf', 8.0, 2.0);
ALTER TABLE PUBLIC.CMR ADD CONSTRAINT PUBLIC.FKRK8E6GJ2H6DAGV1ARKN8D86W9 FOREIGN KEY(ABSENDER_ID) REFERENCES PUBLIC.CMRANSCHRIFT(ID) NOCHECK;
ALTER TABLE PUBLIC.RECHNUNG ADD CONSTRAINT PUBLIC.FKD86IGA42QX7SD96J5UAEPGB8U FOREIGN KEY(ANSCHRIFT_ID) REFERENCES PUBLIC.RECHNUNGSANSCHRIFT(ID) NOCHECK;
ALTER TABLE PUBLIC.RECHNUNG_ZEILE ADD CONSTRAINT PUBLIC.FK8M1J1CURRSL64SO87VU0SLSAE FOREIGN KEY(ZEILE_ID) REFERENCES PUBLIC.RECHNUNGSZEILE(ID) NOCHECK;
ALTER TABLE PUBLIC.RECHNUNG_ZEILE ADD CONSTRAINT PUBLIC.FK7KFNDUBVL7KYAUDXGDMPAG9US FOREIGN KEY(RECHNUNG_ID) REFERENCES PUBLIC.RECHNUNG(ID) NOCHECK;
ALTER TABLE PUBLIC.CMR ADD CONSTRAINT PUBLIC.FKGP2SKE8N5B278BVWG4VS8N2N8 FOREIGN KEY(EMPFAENGER_ID) REFERENCES PUBLIC.CMRANSCHRIFT(ID) NOCHECK;